apiVersion: apps/v1
kind: Deployment
metadata:
  name: froipuy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: froipuy
  template:
    metadata:
      labels:
        app: froipuy
    spec:
      containers:
      - image: okteto.dev/froipuy:latest
        name: froipuy
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "0c6902fc-e1b9-4d56-b601-3f7aa87dd116"
        - name: Vless_Path
          value: "/vlhgyrty5"
        - name: Vmess_UUID
          value: "0c6902fc-e1b9-4d56-b601-3f7aa87dd116"
        - name: Vmess_Path
          value: "/vmnjhgty45"
        - name: Share_Path
          value: "/v2link"
